version: '3.3'

# This system is stable at the moment so try not to break it :P
# @author Alex Pickering

services:
  proxy:
    image: jwilder/nginx-proxy:latest
    container_name: "proxy"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy

  influxdb:
    image: influxdb:1.7.3
    container_name: "${INFLUX_CONTAINER:-influxdab}"
    volumes:
      - ./influxdb:/var/lib/influxdb:rw
    environment:
      INFLUXDB_DB: "${INFLUX_DATABASE:-datasource}"
      INFLUXDB_USER: "${INFLUX_USERNAME:-root}"
      INFLUXDB_USER_PASSWORD: "${INFLUX_PASSWORD:-root}"
    networks:
      - proxy

  telegraf:
    image: telegraf:1.9.2
    container_name: "telegraf"
    volumes: 
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:rw
    environment:
      INFLUXDB_GRAFANA_DB: "${INFLUX_DATABASE:-datasource}"
      INFLUXDB_GRAFANA_USER: "${INFLUX_USERNAME:-root}"
      INFLUXDB_GRAFANA_PW: "${INFLUX_PASSWORD:-root}"
    networks:
      - proxy

  grafana:
    image: grafana/grafana:5.4.3
    container_name: "grafana"
    volumes:
      - ./grafana:/var/lib/grafana:rw
    environment:
      VIRTUAL_HOST: "${GRAFANA_HOST:-grafana}"
    networks:
      - proxy

  chronograf:
    image: chronograf:1.7.7
    container_name: "chronograf"
    volumes:
      - ./chronograf:/var/lib/chronograf:rw
    environment:
      VIRTUAL_HOST: "${CHRONOGRAF_HOST:-chronograf}"
    networks:
      - proxy

networks:
  proxy:
    external: true